"""
NOTE: this code was originally generated by ChatGPT, and is still mostly that (minor edits were made).
I am sorry, I just couldn't be bothered manually implementing complex logic for each OS/toolkit/SDK.

I am welcome to any pull requests to modify this code to make it better,
as chatGPT/LLMs-generated code is never that great.
"""

from __future__ import annotations

import ctypes
import os
import platform
from pathlib import Path
from typing import Mapping, Tuple, Dict, Literal, Any
import tkinter.font as tkFont

from src.system_utils.assets import FONTS
from src.system_utils.system_screen import Screen

# Font Loader

def _load_windows_font(font_path: Path) -> None:
    # AddFontResourceExW(path, FR_PRIVATE, None)
    # FR_PRIVATE = 0x10
    gdi32 = ctypes.windll.gdi32
    gdi32.AddFontResourceExW.argtypes = [ctypes.c_wchar_p, ctypes.c_uint, ctypes.c_void_p] # noqa
    gdi32.AddFontResourceExW.restype = ctypes.c_int                                        # noqa

    FR_PRIVATE = 0x10
    added = gdi32.AddFontResourceExW(str(font_path), FR_PRIVATE, None)                     # noqa
    if added <= 0:
        raise OSError(f"Windows could not load font: {font_path}")

def _load_macos_font(font_path: Path) -> None:
    # CoreText: CTFontManagerRegisterFontsForURL(url, kCTFontManagerScopeProcess, error)
    corefoundation = ctypes.CDLL(
        "/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation"
    )
    coretext = ctypes.CDLL(
        "/System/Library/Frameworks/CoreText.framework/CoreText"
    )

    corefoundation.CFURLCreateFromFileSystemRepresentation.argtypes = [
        ctypes.c_void_p,        # allocator
        ctypes.c_char_p,        # buffer
        ctypes.c_long,          # buffer length
        ctypes.c_bool,          # isDirectory
    ]
    corefoundation.CFURLCreateFromFileSystemRepresentation.restype = ctypes.c_void_p

    coretext.CTFontManagerRegisterFontsForURL.argtypes = [
        ctypes.c_void_p,                 # URL
        ctypes.c_uint32,                 # scope
        ctypes.POINTER(ctypes.c_void_p), # error
    ]
    coretext.CTFontManagerRegisterFontsForURL.restype = ctypes.c_bool

    path_bytes = os.fsencode(str(font_path))
    url = corefoundation.CFURLCreateFromFileSystemRepresentation(
        None, path_bytes, len(path_bytes), False
    )
    if not url:
        raise OSError(f"macOS could not create file URL for: {font_path}")

    # kCTFontManagerScopeProcess = 1
    error = ctypes.c_void_p()
    ok = coretext.CTFontManagerRegisterFontsForURL(url, 1, ctypes.byref(error))
    if not ok:
        raise OSError(f"macOS could not load font: {font_path}")

# TODO: does this logic work?
def _load_linux_font(font_path: Path) -> None:
    # fontconfig application font database
    from ctypes.util import find_library

    libname = find_library("fontconfig")
    if not libname:
        raise OSError("fontconfig library not found")

    fc = ctypes.CDLL(libname)
    fc.FcConfigAppFontAddFile.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
    fc.FcConfigAppFontAddFile.restype = ctypes.c_int

    added = fc.FcConfigAppFontAddFile(None, os.fsencode(str(font_path)))
    if added == 0:
        raise OSError(f"Linux/fontconfig could not load font: {font_path}")


def loadAppFonts(font_map: Mapping[str, str]) -> None:
    """
    font_map: {"Family Name": "/absolute/path/to/font.ttf", ...}

    Call this before creating Tk() if possible.
    """
    system = platform.system()

    for family, raw_path in font_map.items():
        font_path = Path(raw_path).expanduser().resolve()
        if not font_path.exists():
            raise FileNotFoundError(f"Missing font for {family!r}: {font_path}")

        if system == "Windows":
            _load_windows_font(font_path)
        elif system == "Darwin":
            _load_macos_font(font_path)
        elif system == "Linux":
            _load_linux_font(font_path)
        else:
            raise RuntimeError(f"Unsupported platform: {system}")


# Font Mapper

def createScaledFont(root, family: str, size: float | int, weight: Literal["normal", "bold"], slant: Literal["roman", "italic"]) -> tkFont.Font:
    """
    Create and return a tkinter.font.Font sized in pixels (negative size) computed from points & dpi.

    - family: font family name (e.g. "Calibri", "Segoe UI")
    - points: desired point size in the design spec (e.g. 15, 28)
    - dpi: physical DPI obtained from your platform probe (e.g. getScreenInfo)
    - weight: "normal" or "bold"

    Returns a tkFont.Font instance you can pass to ttk.Style.configure(..., font=thatFont).
    """
    px = Screen.px(size)
    # create a named Font (explicitly pass root so fonts are tied to the right Tk instance)
    # use negative px to force pixel-size mode
    fontObj = tkFont.Font(root=root, family=family, size=-px, weight=weight, slant=slant)

    return fontObj

def createFontsForStyle(root, fontSpecs: Dict[str, Tuple[str, float | int, Literal["normal", "bold"], Literal["roman", "italic"]]]) -> Dict[str, tkFont.Font]:
    """
    Convenience: create a dict of fonts from a font specification dict:
      fontSpecs = { logicalName: (family, points), ... }
    Returns { logicalName: tkFont.Font, ... }
    """
    loadAppFonts(FONTS) # load every locally saved font

    created = {}
    for name, spec in fontSpecs.items():
        family = spec[0]
        size   = spec[1]
        weight = spec[2]
        slant  = spec[3]
        created[name] = createScaledFont(root, family, size, weight, slant)
    return created

def applyFontsToStyles(style, mapping: Dict[str, tkFont.Font]):
    """
    Apply fonts to ttk/ttkbootstrap styles.

    mapping key: style name (e.g. 'task.danger.TButton')
    mapping value: tkFont.Font instance (not a tuple)
    """
    for styleName, fontObj in mapping.items():
        style.configure(styleName, font=fontObj)

def applyOptionsToStyles(style, mapping: Dict[str, Dict[Any, Any]]):
    """
    Apply fonts to ttk/ttkbootstrap styles.

    mapping key: style name (e.g. 'task.danger.TButton')
    mapping value: tkFont.Font instance (not a tuple)
    """
    for styleName, options in mapping.items():
        style.configure(styleName, **options)